//  error handling

try{
    console.log(a);
}
catch{
    console.log("There is an error")
}